// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "cs_mattermost_plugin",
  "name": "CobaltStrike Host Notifier",
  "description": "A plugin to notify about CobaltStrike host status",
  "version": "0.1.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "WebhookURL",
        "display_name": "Webhook URL",
        "type": "text",
        "help_text": "The webhook URL for the Mattermost incoming webhook",
        "placeholder": "",
        "default": "",
        "hosting": ""
      }
    ]
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
